### ISSUE TITLE
Heating is faster on boost mode ^^

### ISSUE THREAD

**Issue by Vidalcris** [Ralim/ts100#74]
I'm pretty sure my iron is faster to heat if i press the boost button.
Is this the Pterm that is so low that the power is different depending on the command ?
`pidSettings.kp = 8;
 pidSettings.ki = 1;
 pidSettings.kd = 0; //Not using D atm`

As a geek i would like to be able to change the PID in the menu ;)

**Comment by Ralim** [comment]
I do have a build that allows you to change the PID values. However at the moment increasing any further causes large fluctuations in the tip temperature (control loop is unstable).

I can enable editing the PID in the menu in a special build for you to play with though. I'm more than open to new tuning parameters (just remember I will test them on multiple tips here before I use new ones 😄 )

**Comment by Vidalcris** [comment]
Oh that could be really awesome :p can you also reverse temperature setting and stop on heating mode if this is not too long ? ;)
That will be my firmware for a long time for sure !

**Comment by Ralim** [comment]
What do you mean by the second half?
> can you also reverse temperature setting and stop on heating mode if this is not too long ? ;)

**Comment by Vidalcris** [comment]
I would like to press usb button to stop ;)

**Comment by erpalma** [comment]
Maybe you could simply set the power to 100% until 80/90% of the target temp is reached, then PID kiks in.

**Comment by Vidalcris** [comment]
@erpalma Yeah i think its a really good idea :)

**Comment by thanks4opensource** [comment]
Isn't that the whole point of PID? If you power 100% until 80/90% of target that's open loop -- you're betting you won't over- or undershoot, which will be different for every tip, ambient temperature, airflow, whether you're tinning the tip,  etc., etc.  Then when the PID kicks in it might take more time fixing things up than if it had been running all along.

Control algorithms are hard. :(

**Comment by Vidalcris** [comment]
You are right, but that become part of the PID loop and we are in a sense improving it :)
That could even become a new setting in the menu.

This is not a quadcopter so anyway that will work ^^ (personnaly i dont need a perfect 320° from start, i mean if there is a little jump over the setpoint that is not a big issue. At least for me ;) )

**Comment by erpalma** [comment]
Yes, of course this is far from ideal. But as @Vidalcris said, we are not in a critical application and this solution could be a good compromise. A fine tuned PID is better, but it would probably require tuning by the user since optimal parameters vary with (eg) application and tip. Also a faster startup time is better than a rock solid temperature set point, if this is not the case you could easily disable this feature from the menu. We can try and test this setup, if it does not work we can revert it!

Correct me if I'm wrong :)

**Comment by tigert** [comment]
If precise temperature control is not a critical application for a soldering iron with precise temperature control, I don't know what is.

**Comment by Vidalcris** [comment]
@tigert lol...

**Comment by tigert** [comment]
I mean, it's a simple firmware for a very simple device, a soldering iron. There probably should be some thought on what the scope for the default firmware is - it doesn't feed your dog (yet?) or heat your cup of tea (!) and maybe it shouldnt. 

Because the basic uses are the ones that matter, and the more stuff gets added, there is always the risk of making things more complex, inconsistent and full of hidden features you activate accidentally.

While it might be fun to use the iron as a Sous Vide cooker but that should not mean everybody needs to see the temperature setting for medium rare lamb and salmon...  :-)

**Comment by Vidalcris** [comment]
Heating faster is part of basics features of this iron. Read the description again.
And when i say that this become a part of the PID loop that also mean that with this modification the iron will heat faster and also heat correctly and accurately.
But anyway you are fun ;) lol

**Comment by Vidalcris** [comment]
@Ralim I see that you changed the PID some time ago.
`-	pidSettings.kp = 15;
 -	pidSettings.ki = 2;
 -	pidSettings.kd = 3;
 +	pidSettings.kp = 8;
 +	pidSettings.ki = 1;
 +	pidSettings.kd = 0; //Not using D atm`

Is this change the main reason ?
`-		delayMs(50); //Slow the system down a little bit
 +		delayMs(30); //Slow the system down a little bit`

**Comment by mkninc** [comment]
@Vidalcris I've reimplemented the control loop. Decoupled it from the Display/UI handling. Maybe you could try my version and give me some feedback. 
https://github.com/mkninc/ts100_ng

**Comment by Ralim** [comment]
@Vidalcris There were a few things that led up to that change.
I dropped the delay to speed up the system (which brings in the maximum output from the pid, but from this, I must have bought it in too far and I will be patching this in a day or two when I get time to test further).

I also reduced the filtering on the incoming temperature measurements, which makes it fluctuate a lot more but also means that its much quicker in responding to temperature changes (ie putting on a large pad).

I also fixed up and re-arranged some of the PID code which had some side effects to the way the constants were calculated.

So I then went through a few hours of trying to find a PID setting that worked well at most voltages and didn't oscillate more than ~5C under any load.

I think with the next tuning there might be different tuning parameters based on the input voltage as well.

@mkninc I saw your fork and i'm very interested in merging some of the features to this firmware if that's ok by you?

**Comment by Vidalcris** [comment]
@mkninc i will try it for sure ;)

@Ralim Thanks a lot for the explanation !
I still dont understand why D = 0 and how increasing it cannot help.. but i never did another pid tuning than on quadcopter :p

**Comment by Ralim** [comment]
@Vidalcris It basically had less effect that I was hoping for and added instability under some tests (especially when operating at the high end on higher voltages).

**Comment by mkninc** [comment]
@Ralim Sure, feel free to merge whatever you like :)

**Comment by Ralim** [comment]
@mkninc Awesome, I actually have a 2.0 version I started on about 2 weeks back before a pile of work came up that's a complete re-write from the ground up. I'll try and keep the git possible so you can merge in/out of it if you wish :)

**Comment by Vidalcris** [comment]
@mkninc i just measured the time to get from room temperature to 320°C : 4.95sec !
I will update with the result with Ralim's firmware as soon as possible ;)

**Comment by Ralim** [comment]
Mine will be a bit slower because of the current tunings :/

**Comment by Vidalcris** [comment]
6.40sec for your. But the temperature on screen is way more stable.
On mkninc's firmware when i press boost with a setting of 450 this is moving from 430 to 500.

**Comment by Ralim** [comment]
@Vidalcris Yeah usually to have massively fast rise time means more oscillation is easier to hit. Ideally a midpoint between the two would be ideal 😁 That said if i get 2.0 out it should be nice

**Comment by mkninc** [comment]
@Vidalcris I removed all of the filtering/averaging of the temperature display. But when the target temperature is reached, it should be pretty stable.

**Comment by erpalma** [comment]
@mkninc I've tested your v0.9.1. There is a bit of overshooting (<10°C) at startup but then it's pretty stable. No overshoot for @Ralim but the temperature reaches 377/8 and then slowly goes to 380 in a matter of seconds. I have done no tests on the reaction speed while soldering large pads or wires.

Here is a benchmark between the two versions (from ambient to 380, @19v):
@mkninc 12s, same with turbo
@Ralim 16s, with turbo 15s (maybe a little bit less)

**Comment by dogtopus** [comment]
There is an automated PID tuning routine implemented in Marlin (a 3d printer firmware). Its implemention can be found [here](https://github.com/MarlinFirmware/Marlin/blob/e337df2/Marlin/temperature.cpp#L218) (for reference)

Implement a similar feature in TS100 firmware would easily solve the tuning problem

**Comment by Ralim** [comment]
Would be nice to convert it over.
I would make it a settings menu option to run the algorithm and store the result, though almost all of the tips have very similar responses so it probably isn't necessary to run it on every iron?

Currently looking at moving over to a nice fixed point PID which would make an auto tuner easier to use too.

**Comment by Ralim** [comment]
@erpalma Any chance you would be interested in testing the 2.x beta test release? Should be approaching around 12S by my count thanks to the better drive system.
